Fix exception when parsing a file which worked in 0.12
Started getting an exception after updating to `0.13`: 

```
   NoMethodError:
       undefined method `stream' for #<HexaPDF::Reference [22, 0]>
     # .../hexapdf-0.13.0/lib/hexapdf/type/page.rb:308:in `block in contents'
     # .../hexapdf-0.13.0/lib/hexapdf/type/page.rb:305:in `each'
     # .../hexapdf-0.13.0/lib/hexapdf/type/page.rb:305:in `each_with_object'
     # .../hexapdf-0.13.0/lib/hexapdf/type/page.rb:305:in `contents'
     # .../hexapdf-0.13.0/lib/hexapdf/type/page.rb:455:in `to_form_xobject'
     # .../hexapdf-0.13.0/lib/hexapdf/type/page_tree_node.rb:226:in `block in each_page'
     # .../hexapdf-0.13.0/lib/hexapdf/pdf_array.rb:180:in `block in each'
     # .../hexapdf-0.13.0/lib/hexapdf/pdf_array.rb:180:in `each_index'
     # .../hexapdf-0.13.0/lib/hexapdf/pdf_array.rb:180:in `each'
     # .../hexapdf-0.13.0/lib/hexapdf/type/page_tree_node.rb:224:in `each_page'
     # .../hexapdf-0.13.0/lib/hexapdf/document/pages.rb:131:in `each'
```

This was able to fix my problem.