Fix parsing encrypted indirect objects that should be streams but aren't
If a PDF contains an indirect object that should be a stream, e.g. a
Form XObject, but is stored as a dictionary, HexaPDF currently errors
out with

NoMethodError: undefined method 'filter' for an instance of String

The dictionary itself is correctly parsed. Then it is wrapped with
Document#wrap that sees e.g. /Type /XObject /Subtype /Form and uses the
respective type class to wrap the dictionary. If the type class inherits
from Stream, the #after_data_change method fires. As no stream is
provided (since on file it is a dictionary), data.stream is set to an
empty string.

This is no problem if the file is not encrypted. However, if the file is
additionally encrypted, the SecurityHandler#decrypt methods sees that it
is a stream and assumes that the stream needs to be decrypted. However,
since obj.raw_stream is a String, it errors out.

The fix is to check for this exact case (obj.raw_stream == '') and do
nothing.